### ISSUE TITLE
Review Ticket 3/25

### ISSUE THREAD

**Issue by Archkitten** [Archkitten/m22p1-nitro-code#12]
Scrum Team GitHub pages (3 points)

Project Owner / Sponsor presentation and results of review
1st Code in GitHub
1st Deployment, including hosting plan

**Comment by mistylavender** [comment]
Team Score: 2/3

Project Owner / Sponsor presentation and results of review: participated in team and mentioned owner, don't see results at the moment
1st Code in GitHub: documenting different pages and planned flow chart present
1st Deployment, including hosting plan: may need to add more about the deployment plan beyond the single class
