### ISSUE TITLE
Review Ticket 5/6

### ISSUE THREAD

**Issue by Archkitten** [Archkitten/m22p1-nitro-code#16]
### Overall Score: 3/3

Teacher will grade as follows:

- [ ] How Teacher is able to Visualize ideas...  presentations of running code, GH pages,  and concepts/visuals of future project
- [ ] How Teacher is able to understand features, Issues/Tickets, Project Board, GH Pages, time box, future features, and technicals in the project
- [ ] Overall quality, clarity and presentation of the project

**Comment by 4disease** [comment]
Team RedTailedHawks
3/3
Glow: Solid initial idea, good wireframes
Grow: Maybe elaborate more on how you will create the technical sides of the website (Ex. Typing test)

**Comment by RohanKoshy** [comment]
Team Lebronbots review
3/3
Glow: Well thought out use of SQLite database to have a leaderboard for the Nitro Code times.
Grow: Maybe you could have added into your presentation how the code for the nitro code is generated.

**Comment by HexaDrakon** [comment]
Team Labkit

Points: 3/3

Glows: Well, it looks like a cool website. Nice designs, I think. As a CS major, I'm not actually allowed to have opinions on art.
Grows: Stop trying to give us a 0/30 </3 (also remove the typos in your designs smh)
