### ISSUE TITLE
Navodit's Senior Checkout

### ISSUE THREAD

**Issue by Navodit1603** [Archkitten/m22p1-nitro-code#19]
20 Points - Meeting Tech Guidelines

### Individual Assignments and Completion
Requirements verified and accepted by the sponsor
Presentation at the N@tM 
Presentation and requirement completion provided to the teacher (Thu 6/2, Fri 6/3 for Seniors) [N@TM Photos](https://drive.google.com/drive/folders/1eJyRd4fP4qfzuBscb2GvSxrPP3r0M0uT?usp=sharing) 
1 minute commercial video on project (advertise your accomplishments) (Video)[https://www.youtube.com/watch?v=nMW28fSlreY] 

5 Points: Meeting new tech requirements

###New Tech Requirements include...
Database with multiple tables [Teacher DB Commit](https://github.com/Archkitten/m22p1-nitro-code/commit/2c6ddad837d29d89cc000e3b7d3166033a96ce5a)
Creativity and applications of new Tech feature features to Sponsor Project
Not adding distracting features for Sponsor theme, ie non-applicable games, non-applicable fun zones

5 Points: Teacher Final Assessment

### Documentation of Individual Tech Requirements (GitHub Pages)
Showing Success/Achievement [Wiki with technicals](https://github.com/Archkitten/m22p1-nitro-code/wiki/Navodit's-Contribution)
Self Grade Assessment (Total: Individual and Team)
Documentation of Project, Meeting Tech Guidelines [Github pages](https://archkitten.github.io/m22p1-nitro-code/)
Showing Engagement [Scrum Board](https://github.com/Archkitten/m22p1-nitro-code/projects/1)
Maintaining Master Plan,
Sponsor Assessment (GitHub Pages)
Team Assessment (Team Score)

### Self Score 

- N@TM
        - 4.9/5
        - Stood in my area the whole time.
        - Explained my contribution to everyone that came by. 
        - Did not have a lot of people come to our table causing a lot of downtime. 

- Meeting Tech Guidelines
        - 17.5/20
        - Completed typing speed game (Asked by sponsor)
        - Did not finish teacher database which would display assignemnts
        - Presented at N@TM
        - Requirements were verified by sponsor on review days.

- Meeting new tech requirements
         -  Have DB with multiple tables.
         - Code does not execute
         - Creativity with code typing game
         - 2.5/5

- Documentation
          - 5/5
          - Have all documentation linked above

**Comment by Archkitten** [comment]
## Overall Score: ?/35
### Graded by Arch Huang

-----

### Seed: 5/5
- [N@tM present the entire time](https://drive.google.com/file/d/15hguIjmsYZzGpeIK7tMEfQO-Lkfl01oX/view?usp=sharing)
- In class work was great

-----

### Tech Guidelines: ?/20
- [x] Completed the start of the javascript code typer, the main feature of our website
- [x] Sponsor verified project idea
- [x] [N@tM present the entire time](https://drive.google.com/file/d/15hguIjmsYZzGpeIK7tMEfQO-Lkfl01oX/view?usp=sharing)
- [ ] Will be checked by Mort today or tommorow
- [ ] 1 minute commercial video
